blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/KevinVandy/material-react-table/discussions
    about: Please ask and answer questions here.
  - name: Community Chat
    url: https://discord.gg/5wqyRx6fnm
    about: A dedicated discord server hosted by Kevin Vandy
